# set information to info page /info
info:
  build:
    artifact: '@project.artifactId@'
    group: '@project.groupId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    finalName: '@project.build.finalName@'
    timestamp: '${spring.application.name}:${spring.application.instance_id:${random.value}}'

logging:
  level:
    org.springframework: WARN

server:
  port: 8080
  servletPath: /

spring:

  application:
      name: mongotes


  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017
      database: hoteldatabase
